AppExamen.MVCWEB/Models/ErrorViewModel.cs
namespace AppExamen.MVCWEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppExamen.MVCWEB/Controllers/FarmacosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppExamen.Entidades;
using AppExamen.ConsumeAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AppExamen.MVCWEB.Controllers
{
    public class FarmacosController : Controller
    {
        private string urlApi;
        private readonly string _marcaApi;

        public FarmacosController(IConfiguration configuration)
        {
            urlApi = configuration.GetValue("ApiUrlBase", "") + "/Farmacos";
            _marcaApi = configuration.GetValue("ApiUrlBase", "") + "/MarcaFarmaceuticas";
        }

        // GET: FarmacosController
        public ActionResult Index()
        {
            var data = Crud<Farmaco>.Read(urlApi);
            return View(data);
        }

        // GET: FarmacosController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Farmaco>.Read_ById(urlApi, id);
            return View(data);
        }

        // GET: FarmacosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FarmacosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Farmaco data)
        {
            try
            {
                var newData = Crud<Farmaco>.Create(urlApi, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }

        // GET: FarmacosController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<Farmaco>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: FarmacosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Farmaco data)
        {
            try
            {
                Crud<Farmaco>.Update(urlApi, id, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }

        // GET: FarmacosController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = Crud<Farmaco>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: FarmacosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Farmaco data)
        {
            try
            {
                Crud<Farmaco>.Delete(urlApi, id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }
    }
}

AppExamen.MVCWEB/Controllers/HomeController.cs
using AppExamen.MVCWEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppExamen.MVCWEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppExamen.MVCWEB/Controllers/MarcaFarmaceuticasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppExamen.Entidades;
using AppExamen.ConsumeAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AppExamen.MVCWEB.Controllers
{
    public class MarcaFarmaceuticasController : Controller
    {
        private string urlApi;

        public MarcaFarmaceuticasController (IConfiguration configuration)
        {
            urlApi = configuration.GetValue("ApiUrlBase", "").ToString() + "/MarcaFarmaceuticas";
        }

        // GET: DepartamentosController
        public ActionResult Index()
        {
            var data = Crud<MarcaFarmaceutica>.Read(urlApi);
            return View(data);
        }

        // GET: DepartamentosController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<MarcaFarmaceutica>.Read_ById(urlApi, id);
            return View(data);
        }

        // GET: DepartamentosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepartamentosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MarcaFarmaceutica data)
        {
            try
            {
                var newData = Crud<MarcaFarmaceutica>.Create(urlApi, data);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }

        // GET: DepartamentosController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<MarcaFarmaceutica>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: DepartamentosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MarcaFarmaceutica data)
        {
            try
            {
                Crud<MarcaFarmaceutica>.Update(urlApi, id, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }

        // GET: DepartamentosController/Delete/5    
        public ActionResult Delete(int id)
        {
            var data = Crud<MarcaFarmaceutica>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: DepartamentosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, MarcaFarmaceutica data)
        {
            try
            {
                Crud<MarcaFarmaceutica>.Delete(urlApi, id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(data);
            }
        }
    }
}

AppExamen.MVCWEB/Views/Farmacos/Create.cshtml
@model AppExamen.Entidades.Farmaco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Farmaco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrincipioActivo" class="control-label"></label>
                <input asp-for="PrincipioActivo" class="form-control" />
                <span asp-validation-for="PrincipioActivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dosis" class="control-label"></label>
                <input asp-for="Dosis" class="form-control" />
                <span asp-validation-for="Dosis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormaFarmaceutica" class="control-label"></label>
                <input asp-for="FormaFarmaceutica" class="form-control" />
                <span asp-validation-for="FormaFarmaceutica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label"></label>
                <input asp-for="MarcaId" class="form-control" />
                <span asp-validation-for="MarcaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppExamen.MVCWEB/Views/Farmacos/Delete.cshtml
@model AppExamen.Entidades.Farmaco

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Farmaco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrincipioActivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrincipioActivo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dosis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dosis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FormaFarmaceutica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FormaFarmaceutica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MarcaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppExamen.MVCWEB/Views/Farmacos/Details.cshtml
@model AppExamen.Entidades.Farmaco

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Farmaco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrincipioActivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrincipioActivo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dosis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dosis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FormaFarmaceutica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FormaFarmaceutica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MarcaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AppExamen.MVCWEB/Views/Farmacos/Edit.cshtml
@model AppExamen.Entidades.Farmaco

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Farmaco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrincipioActivo" class="control-label"></label>
                <input asp-for="PrincipioActivo" class="form-control" />
                <span asp-validation-for="PrincipioActivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dosis" class="control-label"></label>
                <input asp-for="Dosis" class="form-control" />
                <span asp-validation-for="Dosis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormaFarmaceutica" class="control-label"></label>
                <input asp-for="FormaFarmaceutica" class="form-control" />
                <span asp-validation-for="FormaFarmaceutica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label"></label>
                <input asp-for="MarcaId" class="form-control" />
                <span asp-validation-for="MarcaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppExamen.MVCWEB/Views/Farmacos/Index.cshtml
@model IEnumerable<AppExamen.Entidades.Farmaco>

@{
    ViewData["Title"] = "Index";
}

<h1 style="color: #007bff;">Index</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<div class="table-responsive" style="background-color: #f0e8d0; padding: 10px;">
    <table class="table table-bordered table-striped" style="background-color: #ffebcd;">
        <thead class="thead-dark" style="background-color: #f8f9fa; color: #212529;">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Principio Activo</th>
                <th>Dosis</th>
                <th>Forma Farmacéutica</th>
                <th>Marca</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                var alternateColor = false;
            }
            @foreach (var item in Model)
            {
                <tr style="background-color: @(alternateColor ? "#ffffff" : "#f2f2f2");">
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.PrincipioActivo)</td>
                    <td>@Html.DisplayFor(modelItem => item.Dosis)</td>
                    <td>@Html.DisplayFor(modelItem => item.FormaFarmaceutica)</td>
                    <td>@Html.DisplayFor(modelItem => item.Marca.Nombre)</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary">Edit</a>
                            <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info">Details</a>
                            <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                alternateColor = !alternateColor;
            }
        </tbody>
    </table>
</div>

AppExamen.MVCWEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppExamen.MVCWEB/Views/MarcaFarmaceuticas/Create.cshtml
@model AppExamen.Entidades.MarcaFarmaceutica

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MarcaFarmaceutica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisOrigen" class="control-label"></label>
                <input asp-for="PaisOrigen" class="form-control" />
                <span asp-validation-for="PaisOrigen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AñoFundacion" class="control-label"></label>
                <input asp-for="AñoFundacion" class="form-control" />
                <span asp-validation-for="AñoFundacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppExamen.MVCWEB/Views/MarcaFarmaceuticas/Delete.cshtml
@model AppExamen.Entidades.MarcaFarmaceutica

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MarcaFarmaceutica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaisOrigen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaisOrigen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AñoFundacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AñoFundacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppExamen.MVCWEB/Views/MarcaFarmaceuticas/Details.cshtml
@model AppExamen.Entidades.MarcaFarmaceutica

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MarcaFarmaceutica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaisOrigen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaisOrigen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AñoFundacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AñoFundacion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AppExamen.MVCWEB/Views/MarcaFarmaceuticas/Edit.cshtml
@model AppExamen.Entidades.MarcaFarmaceutica

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MarcaFarmaceutica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisOrigen" class="control-label"></label>
                <input asp-for="PaisOrigen" class="form-control" />
                <span asp-validation-for="PaisOrigen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AñoFundacion" class="control-label"></label>
                <input asp-for="AñoFundacion" class="form-control" />
                <span asp-validation-for="AñoFundacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppExamen.MVCWEB/Views/MarcaFarmaceuticas/Index.cshtml
@model IEnumerable<AppExamen.Entidades.MarcaFarmaceutica>

@{
    ViewData["Title"] = "Index";
}

<h1 style="color: #007bff;">Index</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<div class="table-responsive" style="background-color: #f0e8d0; padding: 10px;">
    <table class="table table-bordered" style="background-color: #ffebcd;">
        <thead style="background-color: #f8f9fa; color: #212529;">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>País de Origen</th>
                <th>Año de Fundación</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                var alternateColor = false;
            }
            @foreach (var item in Model)
            {
                <tr style="background-color: @(alternateColor ? "#ffffff" : "#f2f2f2");">
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.PaisOrigen)</td>
                    <td>@Html.DisplayFor(modelItem => item.AñoFundacion)</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary">Edit</a>
                            <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info">Details</a>
                            <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                alternateColor = !alternateColor;
            }
        </tbody>
    </table>
</div>

AppExamen.MVCWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppExamen.MVCWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppExamen.MVCWEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppExamen.MVCWEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MarcaFarmaceuticas" asp-action="Index">Marcas Farmaceuticas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farmacos" asp-action="Index">Farmacos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppExamen.MVCWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>